spring:
  datasource:
    url: jdbc:sqlserver://cloud-project-server-team-one.database.windows.net:1433;database=CloudProject
    username: TeamOne
    password: CloudProject1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2016Dialect
  flyway:
    enabled: false
    validate-on-migrate: true